baseURL = 'https://luojiego.com'
languageCode = 'en-us'
title = "Roger's Blog"
theme = 'beautifulhugo'
publishDir = "public/docs"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
